### ISSUE TITLE
Getting error

### ISSUE THREAD

**Issue by benblack75** [Abdulla060/Processing.py-intellisense#3]
This is the output that I get when running in Pycharm:
E:\PROJECTS\CODE\PROCESSING\Processing.py-intellisense-master\venv\Scripts\python.exe -c "import os;os.system('java -jar lib\processing-py.jar Example.py')"
java.lang.UnsatisfiedLinkError: Can't load library: E:\PROJECTS\CODE\PROCESSING\Processing.py-intellisense-master\natives\windows-i586\\gluegen-rt.dll

Do you have any suggestions for getting this library to load?

**Comment by Abdulla060** [comment]
Hello. looks like you are having this issue [#1](https://github.com/Abdulla060/Processing.py-intellisense/issues/1). for some reason, processing.py only works nicely with specific versions of java. try installing the one in the `readme` file

**Comment by benblack75** [comment]
I had two versions installed- I reduced installed versions to version 1.8.202 only, and happy to report that it's working now. Thanks for your help, and for putting this together- I really appreciate it!
